# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: python:3.7.3

test: &test
  step:
    name: Test
    script:
      - python -m pip install --upgrade pip
      - pip install pytest
      - pip install pytest-cov
      - pip install coverage-badge
      - pip install -r requirements.txt
      - pytest --cov-config=.coveragerc --cov=iqmotion iqmotion --cov-fail-under=100
      - coverage-badge -o coverage.svg
    artifacts:
      - coverage.svg
    services:
      - docker

test: &test_branch
  step:
    name: Test
    script:
      - python -m pip install --upgrade pip
      - pip install pytest
      - pip install pytest-cov
      - pip install coverage-badge
      - pip install -r requirements.txt
      - pytest --cov-config=.coveragerc --cov=iqmotion iqmotion 
      - coverage-badge -o coverage.svg
    artifacts:
      - coverage.svg
    services:
      - docker

upload-badge: &upload-badge
  step:
    name: Upload the coverage upload-badge
    script:
      - pipe: docker://bitbucketpipelines/bitbucket-upload-file:0.1.0
        variables:
          BITBUCKET_USERNAME: $BITBUCKET_USERNAME
          BITBUCKET_APP_PASSWORD: $BITBUCKET_APP_PASSWORD
          FILENAME: 'coverage.svg'


push: &push
  step:
    name: Push and Tag
    script:
    - pip install semversioner==0.6.16
    - ./bump-version.sh
    - ./git-tag-and-push.sh

pipelines:
  default:
    - <<: *test_branch
    - <<: *upload-badge
  branches:
    master:
    - <<: *test
    - <<: *upload-badge
    # - <<: *push
