# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: python:3.7.3

test: &test-master
  step:
    name: Test
    script:
      - python -m pip install --upgrade pip
      - pip install pytest
      - pip install pytest-cov
      - pip install coverage-badge
      - pip install -r requirements.txt
      - pytest --cov-config=.coveragerc --cov=iqmotion iqmotion --cov-fail-under=100
      - coverage-badge -o coverage.svg
    artifacts:
      - coverage.svg
    services:
      - docker

test: &test
  step:
    name: Test
    script:
      - python -m pip install --upgrade pip
      - pip install pytest
      - pip install pytest-cov
      - pip install coverage-badge
      - pip install -r requirements.txt
      - pytest --cov-config=.coveragerc --cov=iqmotion iqmotion 
    services:
      - docker

bump-version: &bump-version
  step:
    name: Bump the repository version
    script:
      - python -m pip install --upgrade pip
      - pip install pybadges
      - pip install semversioner
      - ./bump_version.sh
      artifacts:
      - release_badge.svg

upload-cov-badge: &upload-cov-badge
  step:
    name: Upload the coverage badge
    script:
      - pipe: docker://bitbucketpipelines/bitbucket-upload-file:0.1.0
        variables:
          BITBUCKET_USERNAME: $BITBUCKET_USERNAME
          BITBUCKET_APP_PASSWORD: $BITBUCKET_APP_PASSWORD
          FILENAME: 'coverage.svg'

upload-release-badge: &upload-release-badge
  step:
    name: Upload the coverage badge
    script:
      - pipe: docker://bitbucketpipelines/bitbucket-upload-file:0.1.0
        variables:
          BITBUCKET_USERNAME: $BITBUCKET_USERNAME
          BITBUCKET_APP_PASSWORD: $BITBUCKET_APP_PASSWORD
          FILENAME: 'release_badge.svg'

push: &push
  step:
    name: Push and Tag
    script:
    - pip install semversioner==0.6.16
    - ./bump-version.sh
    - ./git-tag-and-push.sh

pipelines:
  default:
    - <<: *test
  branches:
    master:
    - <<: *test-master
    - <<: *upload-cov-badge
    - <<: *bump-version
    - <<: *upload-release-badge
    # - <<: *push
